- name: mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo
- name:
  ansible.builtin.yum:
    name: mongodb-org
    state: installed
- name:
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
- name: replace ip iddress
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0
- name: restart mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted